name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@8e83cea8672e3fbcbb9fdafff34debf6ae4c5f65  # v4.3.5
        with:
          server:       ${{ secrets.FTP_SERVER }}
          username:     ${{ secrets.FTP_USERNAME }}
          password:     ${{ secrets.FTP_PASSWORD }}
          server-dir:   /public_html/
          local-dir:    ./
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            README.md
            .gitignore